api/urls.py
from django.urls import path
from rest_framework.authtoken.views import obtain_auth_token

from . import views

app_name = 'api'

urlpatterns = [
    path('api-token-auth/', obtain_auth_token, name='api-auth-token'),
    path('mailinglist/', views.MailingListCreateListView.as_view(),
         name='api-mailinglist-list'),
    path('mailinglist/<uuid:pk>/',
         views.MailingListRetrieveUpdateDestroyView.as_view(),
         name='api-mailinglist-detail'),
    path('mailinglist/<uuid:mailinglist_pk>/subscribers/',
         views.SubscriberListCreateView.as_view(),
         name='api-subscriber-list'),
    path('subscriber/<uuid:pk>/',
         views.SubscriberRetrieveUpdateDestroyView.as_view(),
         name='api-subscriber-detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mailinglist/', include('mailinglist.urls', namespace='mailinglist')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/v1/', include('api.urls', namespace='api')),
]

mailinglist/urls.py
from django.urls import path

from . import views

app_name = 'mailinglist'

urlpatterns = [
    path('', views.mailinglist_list, name='mailinglist-list'),
    path('add/', views.mailinglist_add, name='mailinglist-add'),
    path('<uuid:pk>/', views.mailinglist_detail, name='mailinglist-detail'),
    path('<uuid:pk>/update/', views.mailinglist_update, name='mailinglist-update'),
    path('<uuid:pk>/delete/', views.mailinglist_delete, name='mailinglist-delete'),
    path(
        '<uuid:pk>/subscribe/',
        views.SubscribeToMailingListView.as_view(),
        name='subscribe',
    ),
    path(
        '<uuid:pk>/thank-you/',
        views.ThankYouForSubscribingView.as_view(),
        name='subscriber-thank-you',
    ),
    path(
        'subscribe/confirmation/<uuid:pk>/',
        views.ConfirmSubscriptionView.as_view(),
        name='confirm-subscription',
    ),
    path('unsubscribe/<uuid:pk>/', views.UnsubscribeView.as_view(), name='unsubscribe'),
    path(
        '<uuid:pk>/message/new/',
        views.MessageCreateView.as_view(),
        name='message-create',
    ),
    path(
        'message/<uuid:pk>/', views.MessageDetailView.as_view(), name='message-detail'
    ),
]

mailinglist/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class MailingList(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='mailinglists',
    )

    def __str__(self) -> str:
        return self.name

    def get_absolute_url(self) -> str:
        return reverse(
            'mailinglist:mailinglist-detail',
            kwargs={'pk': self.id},
        )


class SubscriberManager(models.Manager):
    def confirmed_subscribers_for_mailinglist(self, mailing_list):
        qs = self.get_queryset()
        return qs.filter(confirmed=True, mailing_list=mailing_list)


class Subscriber(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    email = models.EmailField()
    confirmed = models.BooleanField(default=False)
    mailing_list = models.ForeignKey(
        MailingList,
        on_delete=models.CASCADE,
        related_name='subscribers',
    )

    objects = SubscriberManager()

    def __str__(self):
        return self.email

    class Meta:
        unique_together = ['email', 'mailing_list']


class Message(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False,
    )
    mailing_list = models.ForeignKey(
        MailingList,
        on_delete=models.CASCADE,
        related_name='messages',
    )
    subject = models.CharField(max_length=140)
    body = models.TextField()
    started = models.DateTimeField(default=None, null=True)
    finished = models.DateTimeField(default=None, null=True)

    def __str__(self):
        return self.subject

    def get_absolute_url(self):
        return reverse(
            'mailinglist:message-detail',
            kwargs={'pk': self.id},
        )


class SubscriberMessageManager(models.Manager):
    def create_from_message(self, message):
        confirmed_subs = Subscriber.objects.confirmed_subscribers_for_mailinglist(
            message.mailing_list
        )
        return [
            self.create(message=message, subscriber=subscriber)
            for subscriber in confirmed_subs
        ]


class SubscriberMessage(models.Model):
    """
    A model to track whether email is successful sent to a `Subscriber` model.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.ForeignKey(Message, on_delete=models.CASCADE)
    subscriber = models.ForeignKey(Subscriber, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    sent = models.DateTimeField(null=True, default=None)
    last_attempt = models.DateTimeField(null=True, default=None)

    objects = SubscriberMessageManager()

mailinglist/forms.py
from django import forms

from .models import MailingList, Message, Subscriber


class MailingListForm(forms.ModelForm):

    class Meta:
        model = MailingList
        fields = ['name', ]


class SubscriberForm(forms.ModelForm):

    class Meta:
        model = Subscriber
        fields = ['email', ]


class MessageForm(forms.ModelForm):

    class Meta:
        model = Message
        fields = ['subject', 'body', ]

mailinglist/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls.base import reverse_lazy
from django.views import generic

from mailinglist.forms import MailingListForm, MessageForm, SubscriberForm
from mailinglist.mixins import MailingListMixin
from mailinglist.models import MailingList, Message, Subscriber


class MailinglistListView(
    LoginRequiredMixin,
    MailingListMixin,
    generic.ListView,
):
    model = MailingList


mailinglist_list = MailinglistListView.as_view()


class MailinglistDetailView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DetailView,
):
    model = MailingList

    def test_func(self):
        return self.get_object().owner == self.request.user


mailinglist_detail = MailinglistDetailView.as_view()


class MailingListCreateView(LoginRequiredMixin, generic.CreateView):
    model = MailingList
    form_class = MailingListForm
    extra_context = {'page_title': 'Add'}

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


mailinglist_add = MailingListCreateView.as_view()


class MailinglistUpdateView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.UpdateView,
):
    model = MailingList
    form_class = MailingListForm
    extra_context = {'page_title': 'Edit'}

    def test_func(self):
        return self.get_object().owner == self.request.user


mailinglist_update = MailinglistUpdateView.as_view()


class MailinglistDeleteView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DeleteView,
):
    model = MailingList
    success_url = reverse_lazy('mailinglist:mailinglist-list')

    def test_func(self):
        return self.get_object().owner == self.request.user


mailinglist_delete = MailinglistDeleteView.as_view()


class SubscribeToMailingListView(generic.CreateView):
    model = Subscriber
    form_class = SubscriberForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['mailinglist'] = MailingList.objects.get(pk=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        form.instance.mailing_list = MailingList.objects.get(pk=self.kwargs['pk'])
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'mailinglist:subscriber-thank-you',
            kwargs={
                'pk': self.kwargs['pk'],
            },
        )


class ThankYouForSubscribingView(generic.DetailView):
    model = MailingList
    template_name = 'mailinglist/subscription_thank_you.html'


class ConfirmSubscriptionView(generic.DetailView):
    model = Subscriber
    template_name = 'mailinglist/confirm_subscription.html'

    def get_object(self):
        subscriber = super().get_object()
        subscriber.confirmed = True
        subscriber.save()
        return subscriber


class UnsubscribeView(generic.DeleteView):
    model = Subscriber
    template_name = 'mailinglist/unsubscribe.html'

    def get_success_url(self):
        return reverse_lazy(
            'mailinglist:subscribe',
            kwargs={'pk': self.get_object().mailing_list.id},
        )


class MessageCreateView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.CreateView,
):
    SAVE_ACTION = 'save'
    PREVIEW_ACTION = 'preview'

    model = Message
    form_class = MessageForm

    def test_func(self):
        mailinglist = get_object_or_404(MailingList, pk=self.kwargs['pk'])
        return mailinglist.owner == self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        self.mailing_list = get_object_or_404(
            MailingList,
            pk=self.kwargs['pk'],
        )

        context['mailinglist'] = self.mailing_list
        context['SAVE_ACTION'] = self.SAVE_ACTION
        context['PREVIEW_ACTION'] = self.PREVIEW_ACTION
        return context

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == self.PREVIEW_ACTION:
            context = self.get_context_data(form=form, preview=form.instance)
            return self.render_to_response(context=context)
        elif action == self.SAVE_ACTION:
            form.instance.mailing_list = get_object_or_404(
                MailingList,
                pk=self.kwargs['pk'],
            )
            return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy(
            'mailinglist:mailinglist-detail',
            kwargs={'pk': self.kwargs['pk']},
        )


class MessageDetailView(
    LoginRequiredMixin,
    UserPassesTestMixin,
    generic.DetailView,
):
    model = Message

    def test_func(self):
        message = self.get_object()
        return message.mailing_list.owner == self.request.user

mailinglist/templates/mailinglist/confirm_subscription.html
{% extends 'base.html' %}

{% block title %}
Thank you for subscribing to {{ subscriber.mailing_list }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
    <h1>Subscription to {{ subscriber.mailing_list }} is confirmed!</h1>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/mailinglist_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
Confirm Delete {{ object.name }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container pt-4">
  <h1>Confirm Delete?</h1>
  <form method="POST">
    {% csrf_token %}
    <p class="lead">
      Are you sure you want to delete <b>{{ object.name }}</b>?
    </p>
    <button class="btn btn-danger">Yes, Delete</button>
    <a class="btn btn-secondary" href="{% url 'mailinglist:mailinglist-list' %}">No</a>
  </form>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/mailinglist_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ object.name }} Management - {{ block.super }}
{% endblock title %}
{% block content %}
  <div class="container py-3">
    <h1>
      {{ object.name }} Management
      <a class="btn btn-success"
         href="{% url 'mailinglist:mailinglist-update' object.id %}">Edit</a>
      <a class="btn btn-danger"
         href="{% url 'mailinglist:mailinglist-delete' object.id %}">Delete</a>
    </h1>
    <div>
      <a href="{% url 'mailinglist:subscribe' object.id %}">Subscription Link</a>
    </div>
    <div>
      <h2>Messages</h2>
      <a class="btn btn-success"
         href="{% url 'mailinglist:message-create' object.id %}">New Message</a>
      <ul class="pt-3">
        {% for message in object.messages.all %}
          <li>
            <a href="{{ message.get_absolute_url }}">{{ message.subject }}</a>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div>
      <h2>Subscribers</h2>
      <ul>
        {% for subscriber in object.subscribers.all %}
          <li>
            {{ subscriber.email }}
            {{ subscriber.confirmed | yesno | capfirst }}
            <a href="{% url 'mailinglist:unsubscribe' subscriber.id %}">Unsubscribe</a>
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock content %}

mailinglist/templates/mailinglist/mailinglist_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
  {{ page_title }} Mailinglist - {{ block.super }}
{% endblock title %}
{% block content %}
  <div class="container py-3">
    <h1>{{ page_title }} Mailing List</h1>
    <form method="post">
      {% csrf_token %}
      {{ form | crispy }}
      <button class="btn btn-primary">Save</button>
    </form>
  </div>
{% endblock content %}

mailinglist/templates/mailinglist/mailinglist_list.html
{% extends 'base.html' %}

{% block title %}
Mailing List - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
  <h1>Your Mailing Lists</h1>
  <a href="{% url 'mailinglist:mailinglist-add' %}" class="btn btn-primary">New List</a>

  <div class="pt-4">
    <p class="lead">Your mailing lists:</p>
    <ul>
      {% for mailinglist in object_list %}
      <li>
        <a href="{{ mailinglist.get_absolute_url }}">{{ mailinglist.name }}</a>
      </li>
      {% empty %}
      <p>No mailing list yet. Please add one.</p>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/message_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
{{ object.subject }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
  <h1>{{ object.subject }}</h1>

  <div>
    {{ object.body }}
  </div>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/message_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Send a message to {{ mailinglist }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
  <h1>Send a message to {{ mailinglist }}</h1>

  {% if preview %}
  <div class="card my-3">
    <div class="card-header">
      Message Preview
    </div>

    <div class="card-body">
      <h5 class="card-title">
        {{ preview.subject }}
      </h5>
      <div>
        {{ preview.body }}
      </div>
    </div>
  </div>
  {% endif %}

  <form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary" name='action' value="{{ PREVIEW_ACTION }}">Preview</button>
    <button class="btn btn-primary" name='action' value="{{ SAVE_ACTION }}">Save</button>
  </form>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/subscriber_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Subscribe to {{ mailinglist }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
  <h1>Subscribe to {{ mailinglist }}</h1>
  <form method="POST">
    {% csrf_token %}
    {{ form | crispy }}
    <button class="btn btn-primary">Subscribe</button>
  </form>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/subscription_thank_you.html
{% extends 'base.html' %}

{% block title %}
Thank you for subscribing to {{ object.name }} - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
  <h1>Thank you for subscribing to {{ object.name }}</h1>
  <p class="lead">
    Please check your email for confimation mail.
  </p>
</div>
{% endblock content %}

mailinglist/templates/mailinglist/unsubscribe.html
{% extends 'base.html' %}

{% block title %}
Unsubscribe from {{ subscriber.mailing_list }}? - {{ block.super }}
{% endblock title %}

{% block content %}
<div class="container py-3">
    <form method="post">
        {% csrf_token %}
        <p class="lead">
            Are you sure you want to unsubscribe from {{ subscriber.mailing_list }}?
        </p>
        <button class="btn btn-danger">Yes, I want to unsubscribe</button>
    </form>
</div>
{% endblock content %}